[server]
bind = "192.168.122.1"
port = 4519
# if this empty, will use default location ./modules
moduleLocation = ""
# if this empty, will use default location ./lib
libraryLocation = ""
# if this empty, will use default location ./middlewares
middlewareLocation = ""
# if this empty, will use default location ./migrations
migrationLocation = ""
# Authentication server
# Example: 
# authServer = "10.8.0.1:4519"
authServer = ""

[database]
hostname = "localhost"
port = 3306
username = "asep"
password = "dummypass"
database = "ipoint"
